### ISSUE TITLE
Company-Site review

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [SantishaR/Company-Site#1]
Great work and correct code syntax, but however the project could be improved by including the following:

- [ ] section elements to improve sectional semantic markup.
- [ ] contributions, acknowledges and project author details in the readme.MD file. Please refer to the link below on how you can improve your readme. Me file [https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/](URL)

**Comment by SantishaR** [comment]
Thank you so much for the feedback. I have made the improvements to my project.
